name: utho
description: A Flutter alarm clock application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  audioplayers: ^6.0.0
  path_provider: ^2.1.3
  awesome_notifications: ^0.10.1
  http: ^1.2.1
  permission_handler: ^11.3.1
  file_picker: ^8.0.6
  get_it: ^7.7.0 # Add this line
  path: ^1.9.0

  # The following adds the Cupertino Icons font to your application.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/audios/
